name: micro-comms

services:

  # Database services
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  product-db:
    image: postgres
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  sales-db:
    image: mongo
    container_name: sales-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=igor
      - MONGO_INITDB_ROOT_PASSWORD=e296cd9f
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # API services
  auth-api:
    build: './auth-api'
    container_name: auth-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  product-api:
    build: './products-api'
    container_name: products-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082

  # Message broker services
  sales_rabbit:
    image: rabbitmq:4.0-rc-management
    container_name: sales_rabbit
    restart: always
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
