### API Status
GET http://localhost:8081/api/status

### Create Category
POST http://localhost:8081/api/category/
Content-Type: application/json

{
  "description": "Hardware"
}

### GET All Categories
GET http://localhost:8081/api/category/

### GET Category by ID
GET http://localhost:8081/api/category/1

### GET Category by Description
GET http://localhost:8081/api/category/description/Comic

### Create Supplier
POST http://localhost:8081/api/supplier/
Content-Type: application/json

{
  "name": "Walmart"
}

### Create Product
POST http://localhost:8081/api/product/
Content-Type: application/json

{
  "name": "Laptop",
  "quantity_available": 10,
  "supplierId": 1,
  "categoryId": 1
}
