### API Status
GET http://localhost:8081/api/status

### ----------------- CATEGORY -----------------

### GET All Categories
GET http://localhost:8081/api/category/

### GET Category by ID
GET http://localhost:8081/api/category/1

### GET Category by Description
GET http://localhost:8081/api/category/description/Comic


### DELETE Category by ID
DELETE http://localhost:8081/api/category/1

### Create Category
POST http://localhost:8081/api/category/
Content-Type: application/json

{
  "description": "Hardware"
}

### PUT Category by ID
PUT http://localhost:8081/api/category/1002
Content-Type: application/json

{
  "description": "Music"
}

### ----------------- SUPPLIER -----------------

### GET All Suppliers
GET http://localhost:8081/api/supplier/

### GET Supplier by ID
GET http://localhost:8081/api/supplier/1

### GET Supplier by Name
GET http://localhost:8081/api/supplier/name/Walmart


### DELETE Supplier by ID
DELETE http://localhost:8081/api/supplier/52

### Create Supplier
POST http://localhost:8081/api/supplier/
Content-Type: application/json

{
  "name": "Walmart"
}

### PUT Supplier by ID
PUT http://localhost:8081/api/supplier/2
Content-Type: application/json

{
  "name": "Walmart"
}

### ----------------- PRODUCT -----------------

### GET All Products
GET http://localhost:8081/api/product/

### GET Product by ID
GET http://localhost:8081/api/product/202

### GET Product by Name
GET http://localhost:8081/api/product/name/Laptop

### GET Product by Category
GET http://localhost:8081/api/product/category/2

### GET Product by Supplier
GET http://localhost:8081/api/product/supplier/2

### DELETE Product by ID
DELETE http://localhost:8081/api/product/02

### Create Product
POST http://localhost:8081/api/product/
Content-Type: application/json

{
  "name": "Acer",
  "quantity_available": 10,
  "supplierId": 2,
  "categoryId": 2
}

### PUT Product by ID
PUT http://localhost:8081/api/product/202
Content-Type: application/json

{
  "name": "Trackpad",
  "quantity_available": 10,
  "supplierId": 2,
  "categoryId": 2
}
