### API Status
GET http://localhost:8081/api/status

### --------------------------------------------------------CATEGORY--------------------------------------------------------

### ----------------- GET -----------------

### GET All Categories
GET http://localhost:8081/api/category/
Authorization: Bearer <token>

### GET Category by ID
GET http://localhost:8081/api/category/1
Authorization: Bearer <token>


### GET Category by Description
GET http://localhost:8081/api/category/description/Comic
Authorization: Bearer <token>

### ----------------- DELETE -----------------

### DELETE Category by ID
DELETE http://localhost:8081/api/category/1
Authorization: Bearer <token>

### ----------------- PUT -----------------

### PUT Category by ID
PUT http://localhost:8081/api/category/5
Content-Type: application/json
Authorization: Bearer <token>

{
  "description": "Music"
}


### --------------------------------------------------------SUPPLIER--------------------------------------------------------

### ----------------- GET -----------------

### GET All Suppliers
GET http://localhost:8081/api/supplier/
Authorization: Bearer <token>

### GET Supplier by ID
GET http://localhost:8081/api/supplier/1
Authorization: Bearer <token>

### GET Supplier by Name
GET http://localhost:8081/api/supplier/name/Walmart
Authorization: Bearer <token>

### ----------------- DELETE -----------------

### DELETE Supplier by ID
DELETE http://localhost:8081/api/supplier/52
Authorization: Bearer <token>

### ----------------- PUT -----------------

### PUT Supplier by ID
PUT http://localhost:8081/api/supplier/2
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Walmart"
}

### --------------------------------------------------------PRODUCT--------------------------------------------------------

### ----------------- GET -----------------

### GET All Products
GET http://localhost:8081/api/product/
Authorization: Bearer <token>

### GET Product by ID
GET http://localhost:8081/api/product/5
Authorization: Bearer <token>

### GET Product by Name
GET http://localhost:8081/api/product/name/Laptop
Authorization: Bearer <token>

### GET Product by Category
GET http://localhost:8081/api/product/category/2
Authorization: Bearer <token>

### GET Product by Supplier
GET http://localhost:8081/api/product/supplier/2
Authorization: Bearer <token>

### ----------------- DELETE -----------------

### DELETE Product by ID
DELETE http://localhost:8081/api/product/02
Authorization: Bearer <token>

### ----------------- PUT -----------------

### PUT Product by ID
PUT http://localhost:8081/api/product/5
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Star Wars: Jedi Survivor",
  "quantity_available": 350,
  "supplierId": 5,
  "categoryId": 5
}

### --------------------------------------------------------POST--------------------------------------------------------

### ----------------- CATEGORY -----------------

### Create Category 1
POST http://localhost:8081/api/category/
Content-Type: application/json

{
  "description": "Electronics"
}

### Create Category 2
POST http://localhost:8081/api/category/
Content-Type: application/json

{
  "description": "Books"
}

### Create Category 3
POST http://localhost:8081/api/category/
Content-Type: application/json

{
  "description": "Clothing"
}

### Create Category 4
POST http://localhost:8081/api/category/
Content-Type: application/json

{
  "description": "Home Appliances"
}

### Create Category 5
POST http://localhost:8081/api/category/
Content-Type: application/json

{
  "description": "Toys"
}

### ----------------- SUPPLIER -----------------

### Create Supplier 1
POST http://localhost:8081/api/supplier/
Content-Type: application/json

{
  "name": "Amazon"
}

### Create Supplier 2
POST http://localhost:8081/api/supplier/
Content-Type: application/json

{
  "name": "Best Buy"
}

### Create Supplier 3
POST http://localhost:8081/api/supplier/
Content-Type: application/json

{
  "name": "Target"
}

### Create Supplier 4
POST http://localhost:8081/api/supplier/
Content-Type: application/json

{
  "name": "Costco"
}

### Create Supplier 5
POST http://localhost:8081/api/supplier/
Content-Type: application/json

{
  "name": "Walmart"
}

### ----------------- PRODUCT -----------------
### Create Product 1
POST http://localhost:8081/api/product/
Content-Type: application/json

{
  "name": "iPhone 13",
  "quantity_available": 50,
  "supplierId": 1,
  "categoryId": 1
}

### Create Product 2
POST http://localhost:8081/api/product/
Content-Type: application/json

{
  "name": "Harry Potter and the Sorcerer's Stone",
  "quantity_available": 100,
  "supplierId": 2,
  "categoryId": 2
}

### Create Product 3
POST http://localhost:8081/api/product/
Content-Type: application/json

{
  "name": "Levi's Jeans",
  "quantity_available": 200,
  "supplierId": 3,
  "categoryId": 3
}

### Create Product 4
POST http://localhost:8081/api/product/
Content-Type: application/json

{
  "name": "Dyson Vacuum Cleaner",
  "quantity_available": 30,
  "supplierId": 4,
  "categoryId": 4
}

### Create Product 5
POST http://localhost:8081/api/product/
Content-Type: application/json

{
  "name": "Lego Star Wars",
  "quantity_available": 150,
  "supplierId": 5,
  "categoryId": 5
}
