### Create User - JWT John Doe
POST http://localhost:8080/api/user/auth
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "password"
}

### Create User - JWT Jane Doe
POST http://localhost:8080/api/user/auth
Content-Type: application/json

{
  "email": "janedoe@email.com",
  "password": "password"
}

### Get Auth status
GET http://localhost:8080/api/status
Authorization: Bearer <token>


### Get User by Email with JWT
GET http://localhost:8080/api/user/email/johndoe@email.com
Authorization: Bearer <token>
